variables:

  frontStateImage: "registry.nise.gov.bd:$CI_COMMIT_SHORT_SHA"

  #repository library
  imageRepository: "registry.nise.gov.bd"

  #admin frontend
  imageAdminRelease: "true"
  imageAdminAppVersion: "prod-1.15"
  imageAdminRepository: "registry.nise.gov.bd/nise3-cube-client-web-admin"

  #Industry frontend
  imagIndustryeRelease: "true"
  imageIndustryAppVersion: "prod-1.12"
  imageIndustryRepository: "registry.nise.gov.bd/nise3-cube-client-web-industry"

  #nise frontend
  imageNiseRelease: "true"
  imageNiseAppVersion: "prod-1.12"
  imageNiseRepository: "registry.nise.gov.bd/nise3-cube-client-web-nise"

  #ssp frontend
  imageSSPRelease: "true"
  imageSSPAppVersion: "prod-1.11"
  imageSSPRepository: "registry.nise.gov.bd/nise3-cube-client-web-ssp"

  #youth frontend
  imageYouthRelease: "true"
  imageYouthAppVersion: "prod-1.11"
  imageYouthRepository: "registry.nise.gov.bd/nise3-cube-client-web-youth"
