variables:

  frontStateImage: "registry.nise.gov.bd:$CI_COMMIT_SHORT_SHA"

  #repository library
  imageRepository: "registry.nise.gov.bd"

  #admin frontend
  imageAdminRelease: "false"
  imageAdminAppVersion: "2.0.8"
  imageAdminRepository: "registry.nise.gov.bd/nise3-cube-client-web-admin"

  #Industry frontend
  imagIndustryeRelease: "false"
  imageIndustryAppVersion: "2.0.8"
  imageIndustryRepository: "registry.nise.gov.bd/nise3-cube-client-web-industry"

  #nise frontend
  imageNiseRelease: "false"
  imageNiseAppVersion: "2.0.12"
  imageNiseRepository: "registry.nise.gov.bd/nise3-cube-client-web-nise"

  #ssp frontend
  imageSSPRelease: "false"
  imageSSPAppVersion: "2.0.7"
  imageSSPRepository: "registry.nise.gov.bd/nise3-cube-client-web-ssp"

  #youth frontend
  imageYouthRelease: "false"
  imageYouthAppVersion: "2.0.7"
  imageYouthRepository: "registry.nise.gov.bd/nise3-cube-client-web-youth"

  #erpl frontend
  imageYouthRelease: "true"
  imageYouthAppVersion: "1.0.0"
  imageYouthRepository: "registry.nise.gov.bd/nise3-cube-client-web-erpl"